version: '3'

services:
  php:
    container_name: php
    build: ./
    depends_on:
      - database
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"

volumes:
  database_data:
