parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true


    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Service\ScheduleDefaultGenerator: ~
    Service\ScheduleGeneratorInterface: '@Service\ScheduleDefaultGenerator'